### ISSUE TITLE
I was able to successfully deploy this model,but getting model error while infering end point

### ISSUE THREAD

**Issue by bhavanitirumala** [aws-samples/amazon-sagemaker-keras-text-classification#4]
ModelErrorTraceback (most recent call last)
<ipython-input-56-a7b58c8988ed> in <module>()
      1 request = json.dumps({ "input": "Keep frozen"})
----> 3 print(predictor.predict(request).decode('utf-8'))

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/predictor.pyc in predict(self, data, initial_args)
     76 
     77         request_args = self._create_request_args(data, initial_args)
---> 78         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
     79         return self._handle_response(response)
     80 

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/client.pyc in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/botocore/client.pyc in _make_api_call(self, operation_name, api_params)
    659             error_code = parsed_response.get("Error", {}).get("Code")
    660             error_class = self.exceptions.from_code(error_code)
--> 661             raise error_class(parsed_response, operation_name)
    662         else:
    663             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
". See https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-keras-text-classification-2019-03-06-12-56-12-136 in account ....... for more information.

**Comment by elangovana** [comment]
Hi Team,
Can we please fix this error in the labs.  I ran into this problem while running the session at NY Loft :-( 

Here are the steps to replicate the problem
1. Invoke inference 2-3 times even on local testing.  After the first/second attempt it is likely fail with the error described above. If u look at the server logs you will find some error related to graph being empty.
```text
  model.reset_metrics()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1119, in reset_metrics
    m.reset_states()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/metrics.py", line 460, in reset_states
    K.set_value(v, 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/backend.py", line 2847, in set_value
    get_session().run(assign_op, feed_dict={assign_placeholder: value})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1077, in _run
    raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().
```


2. This is related to the fact the Keras models are not thread safe as of the version this code uses. The only work around I could find to avoid this issue is to remove static models and use instance models. Updated code:

```python
# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License").
#   You may not use this file except in compliance with the License.
#   A copy of the License is located at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   or in the "license" file accompanying this file. This file is distributed
#   on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
#   express or implied. See the License for the specific language governing
#   permissions and limitations under the License.
#
# This is the file that implements a flask server to do inferences. It's the file that you will modify to
# implement the scoring for your own algorithm.

from __future__ import print_function

import os
import json
import pickle
import StringIO
import sys
import signal
import traceback
import json
import flask

import tensorflow as tf
import pandas as pd
import numpy as np
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

MAX_LEN = 100
label_index = {'Business':0,'Science & Technology':1,'Entertainment':2,'Health & Medicine':3}
prefix = '/opt/ml/'
model_path = os.path.join(prefix, 'model')
with open(os.path.join(model_path,'tokenizer.pickle'), 'rb') as handle:
    tokenizer = pickle.load(handle)

def get_class_label(prediction):
  for key, value in label_index.iteritems():
    if value == prediction[0]:
      return key

# A singleton for holding the model. This simply loads the model and holds it.
# It has a predict function that does a prediction based on the model and the input data.

class ScoringService(object):
    model = None                # Where we keep the model when it's loaded

 
    def get_model(self):
        """Get the model object for this instance, loading it if it's not already loaded."""

        #with open(os.path.join(model_path, 'decision-tree-model.pkl'), 'r') as inp:
        model = tf.keras.models.load_model(os.path.join(model_path, 'news_breaker.h5'))
        model._make_predict_function()
        graph = tf.get_default_graph()
        return model, graph


    def predict(self, input):
        """For the input, do the predictions and return them.

        Args:
            input (a single news headline): The data on which to do the predictions. """
        clf, graph = self.get_model()
        seq = tokenizer.texts_to_sequences([input])
        d = pad_sequences(seq, maxlen=MAX_LEN)
        with graph.as_default():
            prediction = clf.predict_classes(np.array(d))
        return(get_class_label(prediction))

# The flask app for serving predictions
app = flask.Flask(__name__)

@app.route('/ping', methods=['GET'])
def ping():
    """Determine if the container is working and healthy. In this sample container, we declare
    it healthy if we can load the model successfully."""
    health = ScoringService().get_model() is not None  # You can insert a health check here

    status = 200 if health else 404
    return flask.Response(response='\n', status=status, mimetype='application/json')

@app.route('/invocations', methods=['POST'])
def transformation():
    """Do an inference on a single news headline. """
    data = None

    # Convert from CSV to pandas
    if flask.request.content_type == 'application/json':
        request_json = flask.request.get_json()
        input = request_json.get('input')
    else:
        return flask.Response(response='This predictor only supports JSON format', status=415, mimetype='text/plain')

    #
    # # Do the prediction
    prediction = {
        "result": ScoringService().predict(input)
    }
    return flask.Response(response=json.dumps(prediction), status=200, mimetype='application/json')


```

Ideally we would want to load test model to make sure it doesn't fall during demos :-)

**Comment by psuanm5030** [comment]
Please do fix this.  Just did AWS bootcamp and couldnt complete because of this.  Even more sad was the fact that nobody tried this out before the demo.
